# Generated by Django 4.2.6 on 2023-10-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IMx", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="count",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcount",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
